#!/bin/sh
#MISE description="Lint go"

golangci-lint config verify

# If we're in CI, we rely on golangci/golangci-lint-action@v9 defined in .github/workflows/lint.yml
# so only run this locally:
if [ "$CI" = "true" ]; then
  echo "skipped because CI=true"
else
  golangci-lint run --timeout=30m --fix ./...
fi
