#!/bin/sh
#MISE description="Lint go"

golangci-lint config verify

# If we're in CI, we shouldn't auto-fix anything.
if [ "$CI" = "true" ]; then
  golangci-lint run --timeout=30m ./...
else
  # ..whereas in local dev, that's useful.
  golangci-lint run --timeout=30m --fix ./...
fi
